### PR TITLE
adds josh to the members list for MeNext.  Also adds MeNext as a project

### PR DESCRIPTION
**Pull request by vmutti**

### CODE REVIEW

**Comment by seveibar** [comment]
Could you add your name to the existing "menext" folder? If you do a `git commit --amend` and `git push -f` it should still appear as one commit.

**Comment by vmutti** [comment]
eeeeehhhhhh fine

**Comment by vmutti** [comment]
should be fine now I think

**Comment by seveibar** [comment]
Hey Josh!

We can't automatically merge this because it conflicts with the current version in the repo (somebody else had their name added first)

Try to repush with an updated version without the conflict. I wrote some instructions in https://github.com/rcos/rcos-projects/pull/8

**Comment by vmutti** [comment]
how about now ol' severino

**Comment by seveibar** [comment]
Hahahahahaha thanks!

**Pull request merged**
